[project]
name = "ein-extract"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "pdfplumber>=0.11.7",
    "pypdf2>=3.0.1",
    "requests>=2.32.4",
    "streamlit>=1.47.0",
    "tldextract>=5.3.0",
    "xlsxwriter>=3.2.5",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
